### ISSUE TITLE
plugin issue 

### ISSUE THREAD

**Issue by designel** [ultrabug/mkdocs-static-i18n#155]
Hello, 

I have a problem using the plugin in the documentation, I don't know if someone already faced the same issue as me : 
when trying to serve my doc I have the following error: 
Traceback (most recent call last):
  File "c:\users\Login\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main    
    return _run_code(code, main_globals, None,
  File "c:\users\Login\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Login\AppData\Local\Programs\Python\Python39\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\mkdocs\__main__.py", line 177, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, **kwargs)
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\mkdocs\commands\serve.py", line 54, in serve
    config = builder()
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\mkdocs\commands\serve.py", line 49, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\mkdocs\commands\build.py", line 284, in build
    nav = get_navigation(files, config)
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\mkdocs\structure\nav.py", line 101, in get_navigation
    items = _data_to_navigation(nav_config, files, config)
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\mkdocs\structure\nav.py", line 156, in _data_to_navigation
    return [
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\mkdocs\structure\nav.py", line 157, in <listcomp>
    _data_to_navigation(item, files, config)[0]
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\mkdocs\structure\nav.py", line 149, in _data_to_navigation
    return [
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\mkdocs\structure\nav.py", line 152, in <listcomp>
    Section(title=key, children=_data_to_navigation(value, files, config))
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\mkdocs\structure\nav.py", line 156, in _data_to_navigation
    return [
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\mkdocs\structure\nav.py", line 157, in <listcomp>
    _data_to_navigation(item, files, config)[0]
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\mkdocs\structure\nav.py", line 149, in _data_to_navigation
    return [
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\mkdocs\structure\nav.py", line 150, in <listcomp>
    _data_to_navigation((key, value), files, config)
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\mkdocs\structure\nav.py", line 163, in _data_to_navigation
    file = files.get_file_from_path(path)
  File "c:\users\Login\appdata\local\programs\python\python39\lib\site-packages\mkdocs_static_i18n\folder_structure.py", line 55, in get_file_from_path
    root_folder = expected_src_path.parts[0]
IndexError: tuple index out of range

My configuration in mkdocs.yml is :

plugins: 
  - i18n:
      default_language: !ENV [DEFAULT_LANGUAGE, "en"]
      default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
      docs_structure: folder
      languages:
        en:
          name: English
        fr:
          name: Français

my folder structure is : 

docs:
|__>assets
|__>fr
   |__>doc_en
   |__>Readme.md
|__>en 
   |__>doc_fr
   |__>Readme.md

I don't know if I need to add any things else. 

thank you in advance.

**Comment by designel** [comment]
hello @ultrabug, 

thank you so much for your answer, 
I had an error in the nav section I used in the previous configuration: 
nav: 
  - 'Home': 'path'
  - 'Topic1' : 'path'
 ...

**Comment by ultrabug** [comment]
np mate, closing
