### ISSUE TITLE
Build failing with lt (lithuanian) language

### ISSUE THREAD

**Issue by Delivator** [ultrabug/mkdocs-static-i18n#25]
Building mkdocs fails [after adding Lithuanian files](https://github.com/skynet-guide/skynet-guide.github.io/pull/42) and I don't know why.

For debugging I copied the working English file `docs/index.md` to ``docs/index.lt.md`` to rule out formatting errors, but I still get the same error, so I assume its a bug specifically with lt files.

Error message:
```
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/runner/work/skynet-guide.github.io/skynet-guide.github.io/site 
INFO    -  Building en documentation 
INFO    -  Building fr documentation 
INFO    -  Building de documentation 
INFO    -  Building ru documentation 
INFO    -  Building es documentation 
INFO    -  Building lt documentation 
ERROR   -  Error building page 'index.lt.md': partials/languages/lt.html 
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.10/x64/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/click/core.py", line 1665, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/mkdocs/__main__.py", line 152, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/mkdocs/commands/build.py", line 295, in build
    config['plugins'].run_event('post_build', config=config)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/mkdocs/plugins.py", line 96, in run_event
    result = method(**kwargs)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/mkdocs_static_i18n/plugin.py", line 349, in on_post_build
    _build_page(file.page, config, files, nav, env, dirty)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/mkdocs/commands/build.py", line 210, in _build_page
    output = template.render(context)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/jinja2/environment.py", line 1289, in render
    self.environment.handle_exception()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/jinja2/environment.py", line 924, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/material/main.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/material/base.html", line 4, in top-level template code
    {% import "partials/language.html" as lang with context %}
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/jinja2/environment.py", line 1394, in make_module
    return TemplateModule(self, ctx)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/jinja2/environment.py", line 1524, in __init__
    body_stream = list(template.root_render_func(context))  # type: ignore
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/material/partials/language.html", line 4, in top-level template code
    {% import "partials/languages/" ~ config.theme.language ~ ".html" as lang %}
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/jinja2/loaders.py", line 214, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: partials/languages/lt.html
Error: Process completed with exit code 1.
```

**Comment by ultrabug** [comment]
@Delivator hi, this breaks because mkdocs-material does not support the `lt` locale : https://github.com/squidfunk/mkdocs-material/tree/master/material/partials/languages

What should we expect here that mkdocs-static-i18n do in your opinion?

**Comment by ultrabug** [comment]
The best we could do IMHO would be to inspect the mkdocs-material package and check if the requested language partial file is present, if not fallback to english and issue a warning log instead of breaking the build

What do you think?

**Comment by Delivator** [comment]
Yeah we figured you that the error occurs because `mkdocs-material` doesn't have a Lithuanian language.

I think a fallback to English if the specified language doesn't exist sounds good!

**Comment by ultrabug** [comment]
@Delivator okay, then once I get feedback and merge #26 I will make that happen too

**Comment by ultrabug** [comment]
@Delivator the fix is ready for when #22 will be approved

See https://github.com/ultrabug/mkdocs-static-i18n/pull/27

```
mkdocs build
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /home/alexys/github/mkdocs-static-i18n/site
INFO     -  Building en documentation
INFO     -  Building fr documentation
INFO     -  Building lt documentation
WARNING  -  Language lt is not supported by mkdocs-material==7.1.0, setting 'theme.language: en'
INFO     -  Documentation built in 0.64 seconds
```

**Comment by Delivator** [comment]
Awesome! 🙌

**Comment by ultrabug** [comment]
version 0.13 is there mate
