### ISSUE TITLE
Error during deploying of site with plugin

### ISSUE THREAD

**Issue by Kanaduchi** [ultrabug/mkdocs-static-i18n#56]
I have a problem to deploy site with this plugin into github pages.

You can find trace here: https://github.com/Kanaduchi/vwcoding/runs/3442091472?check_suite_focus=true

I use latest version of mkdocs-material and your plugin:
```mkdocs-material==7.2.5
mkdocs-pdf-export-plugin==0.5.8
mkdocs-print-site-plugin==1.2.3
mkdocs-static-i18n==0.19```

Error:
```Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.6/x64/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/mkdocs/__main__.py", line 204, in gh_deploy_command
    build.build(cfg, dirty=not clean)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/mkdocs/commands/build.py", line 274, in build
    files = config['plugins'].run_event('files', files, config=config)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/site-packages/mkdocs_static_i18n/plugin.py", line 388, in on_files
    self.i18n_configs[language] = deepcopy(config)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 237, in _deepcopy_method
    return type(x)(x.__func__, deepcopy(x.__self__, memo))
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/hostedtoolcache/Python/3.9.6/x64/lib/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'module' object```

**Comment by Kanaduchi** [comment]
Looks like this error appears when I use your plugin together with https://github.com/zhaoterryy/mkdocs-pdf-export-plugin.

How can I fix this problem? I want to use both of these plugins

**Comment by ultrabug** [comment]
The error appends on the `on_config` hook and [as you can see here](https://github.com/zhaoterryy/mkdocs-pdf-export-plugin/blob/master/mkdocs_pdf_export_plugin/plugin.py#L29) the **mkdocs-pdf-export-plugin** does not return a `config` object on this hook as [it is supposed to](https://www.mkdocs.org/dev-guide/plugins/#on_config).

So I advise you to request this to be fixed on the **mkdocs-pdf-export-plugin** plugin instead because there's nothing on my side I can do about a misbehaving third party plugin I'm afraid.

**Comment by Kanaduchi** [comment]
Thank you for research!
We fixed mkdocs-pdf-export-plugin (https://github.com/zhaoterryy/mkdocs-pdf-export-plugin/pull/101/commits/707f71b0bc38c387481674ef0a66e60d7429d5bd) and added return statement. But error is still there
https://github.com/Kanaduchi/vwcoding/runs/3469133569?check_suite_focus=true

I wonder why all other plugins work as expected together with mkdocs-pdf-export-plugin

**Comment by ultrabug** [comment]
> I wonder why all other plugins work as expected together with mkdocs-pdf-export-plugin

Not all plugins do manipulate configuration objects etc... depending on what needs to be done, this can have side effects such as this.

For the record, I'm not happy to have to use `deepcopy` because this is making mkdocs-static-i18n slow.

> But error is still there

Indeed, this means that the pdf plugin does inject or store some kind of unhashable object somewhere... which makes it impossible to deepcopy...

When inspecting the pdf plugin object we get from the config, I see the `renderer` as suspect

```
{'renderer': <mkdocs_pdf_export_plugin.renderer.Renderer object at 0x7fc3255bf4f0>, 'enabled': True, 'combined': False, 'num_files': 0, 'num_errors': 0, 'total_time': 0, 'config': {'media_type': 'print', 'verbose': False, 'enabled_if_env': None, 'combined': False, 'combined_output_path': 'pdf/combined.pdf', 'theme_handler_path': None}}
```

**Comment by ultrabug** [comment]
Got it, indeed the `renderer` object stores a `theme` attribute which is loaded from `_load_theme_handler` and [returns a Python module (which is not hashable)](https://github.com/zhaoterryy/mkdocs-pdf-export-plugin/blob/master/mkdocs_pdf_export_plugin/renderer.py#L81)

So, my first intuition would be to make the pdf plugin lazy load that module instead of having it there

My second thought would be to question why the renderer is initialized in the `on_config` callback while it seems it has nothing to do with it at this stage, it's used afterwards in the `on_nav` element

**Comment by ultrabug** [comment]
[This is the fix you're looking for](https://github.com/zhaoterryy/mkdocs-pdf-export-plugin/pull/102) :star_struck:

**Comment by Kanaduchi** [comment]
@ultrabug Thank you! I've pinged Terry to review and merge changes.

**Comment by ultrabug** [comment]
closing, it's in
