### ISSUE TITLE
Build bug on default language when default lang url is inside a subdirectory. 

### ISSUE THREAD

**Issue by PsychoBitchy** [ultrabug/mkdocs-static-i18n#61]
Hello.
This applies to MkDocs-material.
I don't really know if it's a bug or a plugin use that is out of specs.
Commit: https://github.com/ultrabug/mkdocs-static-i18n/commit/9694c6a07eab24e4b584ddd6a2aa7fae006dcf95
Release 0.20 introduced a much anticipated feature: page context locale switching without going back to the home.
However, if MkDocs is hosted inside a subfolder AND your default locale point to the root of that folder, if you omit the "extra.alternate.url" parameter for the default language (en ) as documented in the mkdocs-material documentation (although it is marked as 'required' it is optional and defaults to ./), mkdocs build will fail.

Consider the following config: 
- The base folder has a variable name depending on deployment, it is set once with the "site_url" parameter.
- the default language folder is the root of mkdocs folder.
- We can't set an extra.alternate.link because we don't know yet the deployment folder url.
- The default lang url isn't set, and gracefully defaults to site_url ... which is handy for this (particular) case
```
extra:
  alternate:
    - name: English
      lang: en
      title: English version
      default: true
    - name: Français
      link: fr
      lang: fr
      title: Version française
```
Building mkdocs with mkdocs-static-i18n 0.20 generates an error because alternate["link"] is undefined.

Error:
```
INFO     -  Building documentation...
INFO     -  Adding 'fr' to the 'plugins.search.lang' option
INFO     -  Cleaning site directory
ERROR    -  Error building page 'index.md': 'link'
Traceback (most recent call last):
  File "/home/XXX/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/XXX/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/XXX/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/XXX/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/XXX/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/XXX/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/XXX/lib/python3.8/site-packages/mkdocs/__main__.py", line 173, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, **kwargs)
  File "/home/XXX/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 54, in serve
    config = builder()
  File "/home/XXX/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 49, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/XXX/lib/python3.8/site-packages/mkdocs/commands/build.py", line 306, in build
    _build_page(file.page, config, doc_files, nav, env, dirty)
  File "/home/XXX/lib/python3.8/site-packages/mkdocs/commands/build.py", line 212, in _build_page
    context = config['plugins'].run_event(
  File "/home/XXX/lib/python3.8/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/home/XXX/lib/python3.8/site-packages/mkdocs_static_i18n/plugin.py", line 560, in on_page_context
    if alternate["link"].endswith("/"):
KeyError: 'link'
```
A quick workaround is to add a single dot (`.`) to the default locale link parameter.
```
extra:
  alternate:
    - name: English
      link: .
      lang: en
      title: English version
      default: true
    - name: Français
      link: fr
      lang: fr
      title: Version française
 ```
 Maybe a conditional should be added in case no value is given?
 
 Thanks for your attention.

**Comment by ultrabug** [comment]
Thank you mate, I added a INFO log for this to help future users
